gcloud run deploy slime-chunk-finder \
    --source=. \
    --platform=managed \
    --region=us-central1 \
    --allow-unauthenticated \
    --no-cpu-throttling \
    --timeout=900s \
    --max-instances=2 \
    --memory=512Mi \
    --cpu=1 \
    --startup-probe="timeoutSeconds=300"
